<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WhiteBoard.InputTests</AssemblyName>
    <RootNamespace>WhiteBoard.InputTests</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AvaloniaTelemetryOptOut>true</AvaloniaTelemetryOptOut>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WhiteBoardApp\WhiteBoard.csproj" />
  </ItemGroup>
</Project>
